---
driver_plugin: vagrant
driver_config:
  use_vagrant_berkshelf_plugin: true
  use_vagrant_provision: true
  require_chef_omnibus: '11.4.4'

provisioner:
  name: chef_solo

platforms:
  - name: centos-5.10
  - name: centos-6.5
    driver_config:
      box: centos-6.5
      box_url: https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box

suites:
  - name: wkhtmltox_default
    run_list:
      - recipe[wkhtmltox::default]
    attributes:
  - name: wkhtmltox_release_0_12_1
    run_list:
      - recipe[wkhtmltox::default]
    attributes:
      wkhtmltopdf:
        version: '0.12.1'
