---
driver_plugin: vagrant
driver_config:
  use_vagrant_berkshelf_plugin: true
  use_vagrant_provision: true
  require_chef_omnibus: '11.4.4'

provisioner:
  name: chef_solo

platforms:
  - name: centos-5.10
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[wkhtmltox::default]
    attributes:
  - name: version_0_12_2_6a13a51
    run_list:
      - recipe[wkhtmltox::default]
    excludes:
      - centos-5.10
    attributes:
      wkhtmltox:
        version: '0.12.2-6a13a51'
